### ISSUE TITLE
Incorrect code block wrapping

### ISSUE THREAD

**Issue by ISSOtm** [blackhole12/blackhole12.github.io#1]
Code blocks simply don't wrap for me.
![image](https://user-images.githubusercontent.com/15271137/51434207-9d68bf00-1c5b-11e9-9363-b40a2bc45399.png)
(Firefox Quantum 64.0.2 (64 bits), on Arch Linux)

Hopefully it's simple to fix, but I've had similar issues solved by a [very dumb and awkward fix...](https://github.com/ISSOtm/gb-asm-tutorial/commit/166c38d0bffe77b68f238bc28a4bbdcca7673511) (another problem was [solved much](https://github.com/ISSOtm/gb-asm-tutorial/commit/91aba033867de63ffa40cf1995c54c396b6be176) [more intuitively](https://github.com/ISSOtm/gb-asm-tutorial/commit/2cb68b05aec8fdd113a8dc1d5c0da26df5fa2cc0), however)

**Comment by blackhole12** [comment]
Code blocks are not supposed to wrap, because this would destroy the formatting (the semantic meaning of `<pre>` is literally that no additional formatting should be done). They are, however, supposed to have scroll bars. This was because several blog posts were not specifying a language for `prism.js`, which has now been corrected.
